# Generated by Django 6.1.1 on 2026-09-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'mundo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('mundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='contenido.mundo')),
            ],
            options={
                'db_table': 'temario',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.IntegerField()),
                ('puntos_max', models.IntegerField()),
                ('temario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='contenido.temario')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mundo_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos_usuario', to='contenido.mundo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='contenido.usuario')),
            ],
            options={
                'db_table': 'progreso_usuario',
            },
        ),
        migrations.CreateModel(
            name='ProgresoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField(default=0)),
                ('intentos', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='contenido.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_actividad', to='contenido.usuario')),
            ],
            options={
                'db_table': 'progreso_actividad',
            },
        ),
    ]
