# Generated by Django 6.1.1 on 2026-09-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.IntegerField()),
                ('puntos_max', models.IntegerField()),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'mundo',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='MatchJuego',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='match_juego', serialize=False, to='actividades.actividad')),
            ],
            options={
                'db_table': 'match_juego',
            },
        ),
        migrations.CreateModel(
            name='Memorama',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memorama', serialize=False, to='actividades.actividad')),
            ],
            options={
                'db_table': 'memorama',
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trivia', serialize=False, to='actividades.actividad')),
            ],
            options={
                'db_table': 'trivia',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='actividades.pregunta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('mundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='actividades.mundo')),
            ],
            options={
                'db_table': 'temario',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='temario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='actividades.temario'),
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mundo_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos_usuario', to='actividades.mundo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='actividades.usuario')),
            ],
            options={
                'db_table': 'progreso_usuario',
            },
        ),
        migrations.CreateModel(
            name='ProgresoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField(default=0)),
                ('intentos', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='actividades.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_actividad', to='actividades.usuario')),
            ],
            options={
                'db_table': 'progreso_actividad',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=200)),
                ('definicion', models.CharField(max_length=500)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='actividades.matchjuego')),
            ],
            options={
                'db_table': 'concepto',
            },
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento_a', models.CharField(max_length=200)),
                ('elemento_b', models.CharField(max_length=200)),
                ('memorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pares', to='actividades.memorama')),
            ],
            options={
                'db_table': 'par',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='actividades.trivia'),
        ),
    ]
