# Generated by Django 6.1.1 on 2026-09-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchJuego',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='match_juego', serialize=False, to='contenido.actividad')),
            ],
            options={
                'db_table': 'match_juego',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=200)),
                ('definicion', models.CharField(max_length=500)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='match.matchjuego')),
            ],
            options={
                'db_table': 'concepto',
            },
        ),
    ]
