# Generated by Django 6.1.1 on 2026-09-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trivia', serialize=False, to='contenido.actividad')),
            ],
            options={
                'db_table': 'trivia',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='trivia.pregunta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='trivia.trivia'),
        ),
    ]
