"""
Django settings for SoftQuest project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlsplit

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / 'env.txt'
if env_file.exists():
    env_bytes = env_file.read_bytes()
    try:
        env_text = env_bytes.decode('utf-16')
    except UnicodeDecodeError:
        env_text = env_bytes.decode('utf-8-sig')
    for env_line in env_text.splitlines():
        env_line = env_line.strip()
        if env_line and not env_line.startswith('#') and '=' in env_line:
            env_name, env_value = env_line.split('=', 1)
            os.environ.setdefault(env_name.strip(), env_value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bxw7rg@b5^3r!e3y%cb#^!6nfwhta)u38dfu*dj6sz^fvt88@9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # aqui van librerias 
    # aqui van las apps del proyecto
    'minijuegos.memorama',
    'minijuegos.trivia',
    'minijuegos.match',
    'contenido', # exploracion de mundos y temarios
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SoftQuest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ruta de la carpeta de los templates
        'DIRS': [
            BASE_DIR / 'contenido' / 'template',
            BASE_DIR / 'minijuegos' / 'memorama' / 'template',
            BASE_DIR / 'minijuegos' / 'trivia' / 'template',
            BASE_DIR / 'minijuegos' / 'match' / 'template',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SoftQuest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
}

if not DATABASES['default']:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
elif 'NUEVA_CONTRASEÑA' in os.environ.get('DATABASE_URL', ''):
    database_parts = urlsplit(os.environ['DATABASE_URL'])
    DATABASES['default']['PASSWORD'] = os.environ.get('PGPASSWORD', '')
    DATABASES['default']['HOST'] = database_parts.hostname
    DATABASES['default']['USER'] = database_parts.username
    DATABASES['default']['NAME'] = database_parts.path.lstrip('/')
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
STATICFILES_DIRS = [
    #squi van las urls de los archivos de estilos
    BASE_DIR / 'contenido' / 'template' / 'style',
    BASE_DIR / 'minijuegos' / 'memorama' / 'template' / 'style',
    BASE_DIR / 'minijuegos' / 'match' / 'template' / 'style',
    BASE_DIR / 'minijuegos' / 'trivia' / 'template' / 'style',
]



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
