# Generated by Django 6.1.1 on 2026-09-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorama',
            fields=[
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memorama', serialize=False, to='contenido.actividad')),
            ],
            options={
                'db_table': 'memorama',
            },
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento_a', models.CharField(max_length=200)),
                ('elemento_b', models.CharField(max_length=200)),
                ('memorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pares', to='memorama.memorama')),
            ],
            options={
                'db_table': 'par',
            },
        ),
    ]
